# This file was generated by GoReleaser. DO NOT EDIT.
cask "ims" do
  version "1.5.0"

  on_macos do
    on_intel do
      url "https://github.com/wyattjoh/ims/releases/download/v#{version}/ims_v#{version}_darwin_amd64.tar.gz"
      sha256 "d8f3795c0fe0e22c81da46d9ce74f0e82a2bdc617460685917a50a1dff777715"
    end
    on_arm do
      url "https://github.com/wyattjoh/ims/releases/download/v#{version}/ims_v#{version}_darwin_arm64.tar.gz"
      sha256 "8da9f67eb295acee23612abb7e1bcf24ff911079e7b9d2d83dbd7b0e3fdf19d3"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/wyattjoh/ims/releases/download/v#{version}/ims_v#{version}_linux_amd64.tar.gz"
      sha256 "6a284ed976e503634698bbea69de267688d48d4570e5988dee31f095f5cab9f1"
    end
    on_arm do
      url "https://github.com/wyattjoh/ims/releases/download/v#{version}/ims_v#{version}_linux_arm64.tar.gz"
      sha256 "aa0e0709ca48e7db9a17a21c8e621e4d6d009fc3617200776b179e71c523c96d"
    end
  end

  name "ims"
  desc "image manipulation service, written in Go"
  homepage "https://github.com/wyattjoh/ims"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ims"

  # No zap stanza required

end
