# This file was generated by GoReleaser. DO NOT EDIT.
cask "ims" do
  version "1.5.3"

  on_macos do
    on_intel do
      sha256 "1ea6d3a4f327c3be0ffdba50cfcbf214c352e08ffc0fdced3c0cb90f32304e0c"
      url "https://github.com/wyattjoh/ims/releases/download/v#{version}/ims_v#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "9281088196a9b5728566f77e992a5ed78cc2a4b4a980c3b70460eacd1068ca22"
      url "https://github.com/wyattjoh/ims/releases/download/v#{version}/ims_v#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b684863053520257eb3a29ee7c4cf9be686615f84dd5338b069a45fd2a63c403"
      url "https://github.com/wyattjoh/ims/releases/download/v#{version}/ims_v#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4ab51b7f420fe9ffeb97d87b2eb1225a93d23204052de7a52040fefca5256cbd"
      url "https://github.com/wyattjoh/ims/releases/download/v#{version}/ims_v#{version}_linux_arm64.tar.gz"
    end
  end

  name "ims"
  desc "image manipulation service, written in Go"
  homepage "https://github.com/wyattjoh/ims"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ims"

  # No zap stanza required

end
