# This file was generated by GoReleaser. DO NOT EDIT.
cask "ims" do
  version "1.5.4"

  on_macos do
    on_intel do
      sha256 "61c9b20bdbd2279463a48f14618c533af1782b865413aea0c9f5ea71958b402d"
      url "https://github.com/wyattjoh/ims/releases/download/v#{version}/ims_v#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b09db1d14f9d124a0ea8172584d70c1ab5defabb60b74aa31e5de92dadaaae81"
      url "https://github.com/wyattjoh/ims/releases/download/v#{version}/ims_v#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4cc63e9e55e5cd166ec333c985e7590d3576789b9f3962f734a9fc9c5d14efc7"
      url "https://github.com/wyattjoh/ims/releases/download/v#{version}/ims_v#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "890845a4e7b8c4fe37e20101107fa3e9632fee030ddb51713982603bfc070661"
      url "https://github.com/wyattjoh/ims/releases/download/v#{version}/ims_v#{version}_linux_arm64.tar.gz"
    end
  end

  name "ims"
  desc "image manipulation service, written in Go"
  homepage "https://github.com/wyattjoh/ims"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ims"

  # No zap stanza required

end
