# This file was generated by GoReleaser. DO NOT EDIT.
cask "vercel-scripts" do
  desc "A powerful Deno-based CLI tool for managing Vercel and Next.js development workflows through an interactive collection of reusable scripts."
  homepage ""
  version "0.1.8"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vss"
  depends_on formula: [
      "jq",
    ]

  on_macos do
    on_arm do
      url "https://github.com/wyattjoh/vercel-scripts/releases/download/v0.1.8/vercel-scripts_0.1.8_darwin_arm64.tar.gz"
      sha256 "2017ae3f2efd3b847f22f2373ae57836a9579640b6db3b062856f4e9747a4588"
    end
  end

  # No zap stanza required
end
