# This file was generated by GoReleaser. DO NOT EDIT.
cask "vercel-scripts" do
  desc "A powerful Deno-based CLI tool for managing Vercel and Next.js development workflows through an interactive collection of reusable scripts."
  homepage ""
  version "0.1.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vercel-scripts"
  depends_on formula: [
      "jq",
    ]

  on_macos do
    on_arm do
      url "https://github.com/wyattjoh/vercel-scripts/releases/download/v0.1.5/vercel-scripts_0.1.5_darwin_arm64.tar.gz"
      sha256 "8176f7bf1ed9b0bdf511f57fc1f8a72db6278cbc287105e6cb9a0e2d1498af76"
    end
  end

  # No zap stanza required
end
