# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CloudflareDdns < Formula
  desc "Cloudflare Dynamic DNS Updater"
  homepage "https://github.com/wyattjoh/cloudflare-ddns"
  version "1.0.17"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/wyattjoh/cloudflare-ddns/releases/download/v1.0.17/cloudflare-ddns_v1.0.17_darwin_amd64.tar.gz"
    sha256 "4ba443b658f1a5b8990b7fe91fd7378779c4b52e556d87419870ceb77ca760d5"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/wyattjoh/cloudflare-ddns/releases/download/v1.0.17/cloudflare-ddns_v1.0.17_linux_amd64.tar.gz"
    sha256 "75aff789b6c6b7129793575aeda4e2663072d5a88f6b556ddbb3ec621eb1f6ba"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/wyattjoh/cloudflare-ddns/releases/download/v1.0.17/cloudflare-ddns_v1.0.17_linux_arm64.tar.gz"
    sha256 "5dd61d6e9ca472da98c87a30ea7e5cae6da3b6a2d17f0a043513a71ad1022f07"
  end

  def install
    bin.install "cloudflare-ddns"
  end

  test do
    system "#{bin}/cloudflare-ddns -v"
  end
end
