# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CloudflareDdns < Formula
  desc "Cloudflare Dynamic DNS Updater"
  homepage "https://github.com/wyattjoh/cloudflare-ddns"
  version "1.0.23"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/wyattjoh/cloudflare-ddns/releases/download/v1.0.23/cloudflare-ddns_v1.0.23_darwin_amd64.tar.gz"
    sha256 "502f3a5d7feb15f430b75e23ab5195b375cd8a82f20963b9bc995ed0916f991b"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/wyattjoh/cloudflare-ddns/releases/download/v1.0.23/cloudflare-ddns_v1.0.23_linux_amd64.tar.gz"
    sha256 "d9fdd724102369795c525ab27d68ca6c359c1e8e56a5044eda7cd588275490de"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/wyattjoh/cloudflare-ddns/releases/download/v1.0.23/cloudflare-ddns_v1.0.23_linux_arm64.tar.gz"
    sha256 "0d04bcca905690a33eae08e32834894bf119dab2b06810cbdfe954752ff988dc"
  end

  def install
    bin.install "cloudflare-ddns"
  end

  test do
    system "#{bin}/cloudflare-ddns -v"
  end
end
