# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitPublish < Formula
  desc "git branch publisher"
  homepage "https://github.com/wyattjoh/git-publish"
  version "1.0.8"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wyattjoh/git-publish/releases/download/v1.0.8/git-publish_v1.0.8_darwin_amd64.tar.gz"
      sha256 "644fa6e993704abf41be2a1297b3148bb4537082d35be27b574525ec28ade28d"

      def install
        bin.install "git-publish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wyattjoh/git-publish/releases/download/v1.0.8/git-publish_v1.0.8_darwin_arm64.tar.gz"
      sha256 "a539c90f80787e6f2ed9ea2fc3cb406985dad575c4636a05cdc73d253e1907f4"

      def install
        bin.install "git-publish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/wyattjoh/git-publish/releases/download/v1.0.8/git-publish_v1.0.8_linux_amd64.tar.gz"
      sha256 "d28eefdfce707cfb2a9ff23ddc15730d8fba440470744695057f1fb53bae1981"

      def install
        bin.install "git-publish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wyattjoh/git-publish/releases/download/v1.0.8/git-publish_v1.0.8_linux_arm64.tar.gz"
      sha256 "861f6163938d0ae6e4786f4a0ddb391d5626739a04a02b88ca954382f16be81f"

      def install
        bin.install "git-publish"
      end
    end
  end

  test do
    system "#{bin}/git-publish -v"
  end
end
