# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitPublish < Formula
  desc "git branch publisher"
  homepage "https://github.com/wyattjoh/git-publish"
  version "1.0.7"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/wyattjoh/git-publish/releases/download/v1.0.7/git-publish_v1.0.7_darwin_amd64.tar.gz"
    sha256 "f0ee37449485a8f37fdd867cc8a87f1c8350b696edae80e85fb39452e9fa1513"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/wyattjoh/git-publish/releases/download/v1.0.7/git-publish_v1.0.7_linux_amd64.tar.gz"
    sha256 "a120ae703fb4c308bc5fb4b96fbe8d266142e30a0a380f5691a1d367648fe55e"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/wyattjoh/git-publish/releases/download/v1.0.7/git-publish_v1.0.7_linux_arm64.tar.gz"
    sha256 "813dc7bda6fde6b36aa0a6a0a2583f0a549c2097603ec4c1d8684bbb53c13ec0"
  end

  def install
    bin.install "git-publish"
  end

  test do
    system "#{bin}/git-publish -v"
  end
end
