# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ims < Formula
  desc "image manipulation service, written in Go"
  homepage "https://github.com/wyattjoh/ims"
  version "1.3.7"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/wyattjoh/ims/releases/download/v1.3.7/ims_v1.3.7_darwin_amd64.tar.gz"
    sha256 "6b5debf4435378bc60d5e247907bf13cb394b9e6c0ed270b1a31decf33a51e62"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/wyattjoh/ims/releases/download/v1.3.7/ims_v1.3.7_linux_amd64.tar.gz"
    sha256 "2f4cef4fa7b1ea7d33a33e5ab9eb34ed7485a9fb07bf2eca9fb134a8f15f1b1f"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/wyattjoh/ims/releases/download/v1.3.7/ims_v1.3.7_linux_arm64.tar.gz"
    sha256 "9b6c708cf9e72a542c456884abd7260aaeada5d610f79b7c50a54b02991df25a"
  end

  def install
    bin.install "ims"
  end

  test do
    system "#{bin}/ims -v"
  end
end
