# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ims < Formula
  desc "image manipulation service, written in Go"
  homepage "https://github.com/wyattjoh/ims"
  version "1.4.11"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wyattjoh/ims/releases/download/v1.4.11/ims_v1.4.11_darwin_amd64.tar.gz"
      sha256 "6d80fd9fe726ed5aa4b073b9d35c38d83f4ed3340cb9667b7ebaaa8fbae349d8"

      def install
        bin.install "ims"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wyattjoh/ims/releases/download/v1.4.11/ims_v1.4.11_darwin_arm64.tar.gz"
      sha256 "2b170b7881070762892ca8ce3840a7c632e73e3762cb1cbd530faf71ed37b529"

      def install
        bin.install "ims"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/wyattjoh/ims/releases/download/v1.4.11/ims_v1.4.11_linux_amd64.tar.gz"
      sha256 "3e382f20e47dbfaea9c2a7dbbce5b65af34086b56a564ea752b94ffd9c8c8499"

      def install
        bin.install "ims"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wyattjoh/ims/releases/download/v1.4.11/ims_v1.4.11_linux_arm64.tar.gz"
      sha256 "1ff6647ac1b3521b21cd6fb7c049cdedb3317221385dc453739e5aa38aa5ac2a"

      def install
        bin.install "ims"
      end
    end
  end

  test do
    system "#{bin}/ims -v"
  end
end
