# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jwt < Formula
  desc "JWT Inspector"
  homepage "https://github.com/wyattjoh/jwt"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wyattjoh/jwt/releases/download/v0.1.2/jwt_v0.1.2_darwin_amd64.tar.gz"
      sha256 "8e89a5702fcd44af4f71612de0e52d2e26a24eeb7f39b72dbd4a511a0e21556f"

      def install
        bin.install "jwt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/wyattjoh/jwt/releases/download/v0.1.2/jwt_v0.1.2_linux_amd64.tar.gz"
      sha256 "054133427167b18d40dd09327545ee8288639167ceca85e77bc67147dee17aea"

      def install
        bin.install "jwt"
      end
    end
  end

  test do
    system "#{bin}/jwt -v"
  end
end
