# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jwt < Formula
  desc "JWT Inspector"
  homepage "https://github.com/wyattjoh/jwt"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wyattjoh/jwt/releases/download/v0.1.1/jwt_v0.1.1_darwin_amd64.tar.gz"
      sha256 "57b7034e77388de8d9f4251dc1ba57197d4f088a5c4e8298e4f93dc9736a57f1"

      def install
        bin.install "jwt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/wyattjoh/jwt/releases/download/v0.1.1/jwt_v0.1.1_linux_amd64.tar.gz"
      sha256 "d0164fee9023a7890c7df5d42c605c41db0860912ef62c60911914a32d0eaa17"

      def install
        bin.install "jwt"
      end
    end
  end

  test do
    system "#{bin}/jwt -v"
  end
end
