# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jwt < Formula
  desc "JWT Inspector"
  homepage "https://github.com/wyattjoh/jwt"
  version "0.1.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/wyattjoh/jwt/releases/download/v0.1.3/jwt_v0.1.3_darwin_arm64.tar.gz"
      sha256 "de4e148d1e7b992d974b9019b8b9a99386d888dd16ef6c4c1cc45c84a6199317"

      def install
        bin.install "jwt"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/wyattjoh/jwt/releases/download/v0.1.3/jwt_v0.1.3_darwin_amd64.tar.gz"
      sha256 "f651ece9b2f6d0d0e5dd9ed9f4dbd584ddded2b1d2f48f267e82c777af0d3c11"

      def install
        bin.install "jwt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wyattjoh/jwt/releases/download/v0.1.3/jwt_v0.1.3_linux_arm64.tar.gz"
      sha256 "e8a278303166b34b11b32fa5da83ddd195b5d7d457cf125801c11ee6ce1bfa31"

      def install
        bin.install "jwt"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/wyattjoh/jwt/releases/download/v0.1.3/jwt_v0.1.3_linux_amd64.tar.gz"
      sha256 "d90df0c1b3269cab9fd4d37b59ca9c72c947197a6826361a2852d1779ff93120"

      def install
        bin.install "jwt"
      end
    end
  end

  test do
    system "#{bin}/jwt -v"
  end
end
