# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class YdnsUpdater < Formula
  desc "YDNS DNS Updater"
  homepage "https://github.com/wyattjoh/ydns-updater"
  version "3.0.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/wyattjoh/ydns-updater/releases/download/v3.0.0/ydns-updater_v3.0.0_darwin_amd64.tar.gz"
    sha256 "8674ce7af928fdf4908f5cc09b89ee2016df8e385298bfd8435b8e940353c4df"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/wyattjoh/ydns-updater/releases/download/v3.0.0/ydns-updater_v3.0.0_linux_amd64.tar.gz"
    sha256 "858f14db649afb326b81281a5799bfa22cb57218067efcff5a7f1894c5d2e8e4"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/wyattjoh/ydns-updater/releases/download/v3.0.0/ydns-updater_v3.0.0_linux_arm64.tar.gz"
    sha256 "84ef3f34290e250f7ff319275f3928816c039071e1173456f161550d94a61fa3"
  end

  def install
    bin.install "ydns-updater"
  end

  test do
    system "#{bin}/ydns-updater -v"
  end
end
